package boyermoore;

/**
 *
 * @author ACMarlon
 */
public class Resultados extends javax.swing.JFrame {

    /**
     * Creates new form PantallaFrame
     */
    public Resultados() {
        initComponents();
    }

    public void setResultado(String palabraBuscada, boolean encontrado, String numero, String textoResaltado, String textoInv, String textoInvPal) {
        palabraBuscadaTF.setText(palabraBuscada);
        if (encontrado) {
            palabraEncontradaTF.setText("Si");
            numOcurrenciasTF.setText(numero);
            textoResaltadoTA.setText(textoResaltado);
            textoInvTA.setText(textoInv);
            textoInvPalTA.setText(textoInvPal);
        } else {
            palabraEncontradaTF.setText("No");
            numOcurrenciasTF.setText("0");
            textoResaltadoTA.setText(textoResaltado);
            textoInvTA.setText(textoInv);
            textoInvPalTA.setText(textoInvPal);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        tituloLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoInvPalTA = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        palabraEncontradaLBL = new javax.swing.JLabel();
        palabraBuscadaLBL = new javax.swing.JLabel();
        numeroOcurrLBL = new javax.swing.JLabel();
        palabraBuscadaTF = new javax.swing.JTextField();
        palabraEncontradaTF = new javax.swing.JTextField();
        numOcurrenciasTF = new javax.swing.JTextField();
        textoInvLBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoResaltadoTA = new javax.swing.JTextArea();
        textoInvPalLBL = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoInvTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto1");
        setResizable(false);

        tituloLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloLBL.setText("Resultados");

        textoInvPalTA.setEditable(false);
        textoInvPalTA.setColumns(20);
        textoInvPalTA.setRows(5);
        jScrollPane1.setViewportView(textoInvPalTA);

        palabraEncontradaLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        palabraEncontradaLBL.setText("Palabra encontrada:");

        palabraBuscadaLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        palabraBuscadaLBL.setText("Palabra buscada:");

        numeroOcurrLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numeroOcurrLBL.setText("Número de ocurrencias:");

        palabraBuscadaTF.setEditable(false);

        palabraEncontradaTF.setEditable(false);

        numOcurrenciasTF.setEditable(false);

        textoInvLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoInvLBL.setText("Texto invertido (todos los caracteres):");

        textoResaltadoTA.setEditable(false);
        textoResaltadoTA.setColumns(20);
        textoResaltadoTA.setRows(5);
        jScrollPane2.setViewportView(textoResaltadoTA);

        textoInvPalLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoInvPalLBL.setText("Texto invertido (el orden de las palabras):");

        textoInvTA.setEditable(false);
        textoInvTA.setColumns(20);
        textoInvTA.setRows(5);
        jScrollPane3.setViewportView(textoInvTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(palabraBuscadaLBL)
                            .addComponent(palabraEncontradaLBL)
                            .addComponent(numeroOcurrLBL))
                        .addGap(18, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numOcurrenciasTF, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palabraEncontradaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palabraBuscadaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(409, 409, 409))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(347, 347, 347)
                                .addComponent(tituloLBL))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textoInvPalLBL)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoInvLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloLBL)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(palabraBuscadaLBL))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(palabraBuscadaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(palabraEncontradaLBL))
                    .addComponent(palabraEncontradaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroOcurrLBL)
                    .addComponent(numOcurrenciasTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(192, 192, 192)
                .addComponent(textoInvLBL)
                .addGap(180, 180, 180)
                .addComponent(textoInvPalLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(410, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(385, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(210, 210, 210)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField numOcurrenciasTF;
    private javax.swing.JLabel numeroOcurrLBL;
    private javax.swing.JLabel palabraBuscadaLBL;
    private javax.swing.JTextField palabraBuscadaTF;
    private javax.swing.JLabel palabraEncontradaLBL;
    private javax.swing.JTextField palabraEncontradaTF;
    private javax.swing.JLabel textoInvLBL;
    private javax.swing.JLabel textoInvPalLBL;
    private javax.swing.JTextArea textoInvPalTA;
    private javax.swing.JTextArea textoInvTA;
    private javax.swing.JTextArea textoResaltadoTA;
    private javax.swing.JLabel tituloLBL;
    // End of variables declaration//GEN-END:variables

}
